/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apk_kasir;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class PelangganForm extends javax.swing.JFrame {
    Connection con;
    DefaultTableModel tm;
    
    private void connect(){
        con = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir_anggie", "root", "");
        }catch(Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n" + e );
        }
    }
    
    private void refreshTable(){
        tm = new DefaultTableModel(
            null,
            new Object[] {"ID PELANGGAN", "NAMA PELANGGAN", "ALAMAT", "NO TELP",});
        tb_pelanggan.setModel(tm);
        tm.getDataVector().removeAllElements();
        
        try{
            PreparedStatement s = con.prepareStatement("SELECT * FROM pelanggan");
            ResultSet r = s.executeQuery();
            while(r.next()){
                Object[] data = {
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4)
                };
                tm.addRow(data);
            }
        }catch(Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
    }
    


    /**
     * Creates new form PelangganForm
     */
    public PelangganForm() {
        initComponents();
        connect();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idpel = new javax.swing.JTextField();
        telp = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        al = new javax.swing.JTextArea();
        jbadd = new javax.swing.JButton();
        jbupdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_pelanggan = new javax.swing.JTable();
        jbsearch = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jbdelete = new javax.swing.JButton();
        jbback = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Id Pelanggan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Nama Pelanggan");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("No Telp");

        idpel.setBackground(new java.awt.Color(204, 204, 255));
        idpel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idpel.setForeground(new java.awt.Color(0, 51, 102));
        idpel.setOpaque(false);

        telp.setBackground(new java.awt.Color(204, 204, 255));
        telp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telp.setForeground(new java.awt.Color(0, 51, 102));
        telp.setOpaque(false);

        nama.setBackground(new java.awt.Color(204, 204, 255));
        nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 51, 102));
        nama.setOpaque(false);

        al.setBackground(new java.awt.Color(204, 204, 255));
        al.setColumns(20);
        al.setForeground(new java.awt.Color(0, 51, 102));
        al.setRows(5);
        al.setOpaque(false);
        jScrollPane1.setViewportView(al);

        jbadd.setBackground(new java.awt.Color(204, 204, 255));
        jbadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbadd.setForeground(new java.awt.Color(0, 51, 102));
        jbadd.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\add.png")); // NOI18N
        jbadd.setText("SAVE");
        jbadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaddActionPerformed(evt);
            }
        });

        jbupdate.setBackground(new java.awt.Color(204, 204, 255));
        jbupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbupdate.setForeground(new java.awt.Color(0, 51, 102));
        jbupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\edit.png")); // NOI18N
        jbupdate.setText("UPDATE");
        jbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdateActionPerformed(evt);
            }
        });

        tb_pelanggan.setBackground(new java.awt.Color(204, 204, 255));
        tb_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_pelanggan);

        jbsearch.setBackground(new java.awt.Color(204, 204, 255));
        jbsearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbsearch.setForeground(new java.awt.Color(0, 51, 102));
        jbsearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\cari.png")); // NOI18N
        jbsearch.setText("SEARCH DATA");
        jbsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsearchActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(204, 204, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 51, 102));
        jTextField4.setOpaque(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jbdelete.setBackground(new java.awt.Color(204, 204, 255));
        jbdelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbdelete.setForeground(new java.awt.Color(0, 51, 102));
        jbdelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\hapus.png")); // NOI18N
        jbdelete.setText("DELETE");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });

        jbback.setBackground(new java.awt.Color(204, 204, 255));
        jbback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbback.setForeground(new java.awt.Color(0, 51, 102));
        jbback.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\back.png")); // NOI18N
        jbback.setText("BACK");
        jbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbackActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("DATA PELANGGAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbsearch)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbback, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idpel)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 79, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbadd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbupdate))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(232, 232, 232))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbsearch)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbupdate)
                        .addComponent(jbdelete)
                        .addComponent(jbadd))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addComponent(jbback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 820, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/bg_form.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 870, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaddActionPerformed
    // TODO add your handling code here:
    try{
    PreparedStatement ps = con.prepareStatement("INSERT INTO pelanggan VALUES (?,?,?,?)");
    ps.setString(1, idpel.getText());
    ps.setString(2, nama.getText());
    ps.setString(3, al.getText());
    ps.setString(4, telp.getText());
    ps.executeUpdate();
    idpel.setText("");
    nama.setText("");
    telp.setText("");
    al.setText("");
    idpel.requestFocus();
    refreshTable();   
    } catch(Exception e) {
    System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
    }
    }//GEN-LAST:event_jbaddActionPerformed

    private void jbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdateActionPerformed
    // TODO add your handling code here:
    try {
    PreparedStatement ps = con.prepareStatement(
    "UPDATE pelanggan SET nama_pelanggan=?, alamat=?, no_telp=? where id_pelanggan=?");
    ps.setString(1, nama.getText());
    ps.setString(2, al.getText());
    ps.setString(3, telp.getText());
    ps.setString(4, idpel.getText());
    ps.executeUpdate();
    refreshTable();    
    } catch(Exception e) {
    System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
    }
    }//GEN-LAST:event_jbupdateActionPerformed

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
    // TODO add your handling code here:
    int ok = JOptionPane.showConfirmDialog(null,"Yakin mau dihapus='"+ 
        idpel.getText()+"'",".:: Konfirmasi ::.", JOptionPane.YES_NO_CANCEL_OPTION);
    if (ok==0){
    try {
    PreparedStatement ps = con.prepareStatement("DELETE FROM pelanggan WHERE id_pelanggan=?");
    ps.setString(1, idpel.getText());
    ps.executeUpdate();
    refreshTable(); 
    }catch(Exception e) {
    System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
    }
    }
        
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jbsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsearchActionPerformed
        // TODO add your handling code here:
        tm = new DefaultTableModel (null,
        new Object[] {"id_pelanggan","nama_pelanggan","no_telp","alamat"});
        tb_pelanggan.setModel(tm);
        tm.getDataVector().removeAllElements();
        try
        {
         PreparedStatement s = con.prepareStatement("SELECT*FROM pelanggan where nama_pelanggan LIKE '%" + jbsearch.getText().toString() +"%'");
         ResultSet r = s.executeQuery();
         while(r.next())
         {
             Object[] data ={
             r.getString(1),
             r.getString(2),
             r.getString(3),
             r.getString(4),
             };
         tm.addRow(data);
         }
         
        }
        catch(Exception e)
        {
        System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
        
    }//GEN-LAST:event_jbsearchActionPerformed

    private void tb_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pelangganMouseClicked
    // TODO add your handling code here:
    int i = tb_pelanggan.getSelectedRow();
    if (i== -1){
        return;
    }
    String id_pel = (String) tm.getValueAt(i, 0);
    idpel.setText(id_pel);
    String namapel = (String) tm.getValueAt(i, 1);
    nama.setText(namapel);
    String notelp = (String) tm.getValueAt(i, 2);
    telp.setText(notelp);
    String alamat = (String) tm.getValueAt(i, 3);
    al.setText(alamat);
    }//GEN-LAST:event_tb_pelangganMouseClicked

    private void jbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbackActionPerformed
    // TODO add your handling code here:
    dispose();    
    }//GEN-LAST:event_jbbackActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PelangganForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea al;
    private javax.swing.JTextField idpel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbadd;
    private javax.swing.JButton jbback;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbsearch;
    private javax.swing.JButton jbupdate;
    private javax.swing.JTextField nama;
    private javax.swing.JTable tb_pelanggan;
    private javax.swing.JTextField telp;
    // End of variables declaration//GEN-END:variables
}
